In [1]:
import numpy as np

arr = np.array((1,2,3,4,5))

print(arr +1)

[2 3 4 5 6]


In [3]:
#using scalar operations error came

import numpy as np

arr = np.array((1,2,3,4,5))
a = arr +=1
print(a)

SyntaxError: invalid syntax (<ipython-input-3-441bcf01005b>, line 6)

In [4]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

arr = arr1 +arr2
arr1 = arr1 *arr2

print(arr)
print("\n",arr1)

[[ 6  8]
 [10 12]]

 [[ 5 12]
 [21 32]]


In [8]:
import math
def variance (data,ddof=0):
    n = len(data)
    mean = sum(data)/n
    return sum ((x-mean)**2 for x in data)/(n-ddof)

def stdev(data):
    var = variance(data)
    std_dev= math.sqrt(var)
    return std_dev

stdev([4,8,6,5,3,2,8,8,9,2,5])

2.4257571025684244

In [ ]:
import numpy as np

arr = np.asarray([[[[1,11],[2,22],[3,33]],
                   [[4,44],[5,55],[6,66]]],
                  [[[7,77],[8,88],[9,99]]